### ISSUE TITLE
Schema changes from other Issues

### ISSUE THREAD

**Issue by stoewer** [G-Node/GCA-Web#309]
Collection of schema changes

* [x] Character limit #293 and #312
* [x] Mobile app info #304 #303 #302 #301 
* [x] Active switch for unpublished conferences #295
* [x] Abstract editor: conditional display of fields #300
* [x] Conference short unique #281 
* [x] ctime for entities #287
